version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: cimg/base:stable
    resource_class: medium

jobs:
  build:
    executor: dotnet-executor
    environment:
      IMAGE_NAME: ayazumman.xyz/circleci/sad-final
    steps:
      - checkout

      - run:
          name: Install .NET SDK
          command: |
            curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel LTS
            echo 'export PATH=$PATH:/home/circleci/.dotnet' >> $BASH_ENV

      - run:
          name: Inject Kestrel HTTPS Configuration
          command: |
            sed -i '/var app = builder.Build();/i \
            builder.WebHost.ConfigureKestrel(options => { \
                options.ListenAnyIP(443, listenOptions => { \
                    listenOptions.UseHttps("/etc/ssl/certs/certificate.pfx", "YourSecurePassword"); \
                }); \
            });' API/Program.cs

      - run:
          name: Restore and Build
          command: |
            source $BASH_ENV
            dotnet restore
            dotnet build

      - run:
          name: Run Tests
          command: dotnet test

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Build Image with Buildpacks
          command: |
            curl -sSL https://github.com/buildpacks/pack/releases/download/v0.35.1/pack-v0.35.1-linux.tgz | tar xz
            sudo mv pack /usr/local/bin/pack
            pack build sad-final --path . --builder gcr.io/buildpacks/builder:google-22 --env "GOOGLE_BUILDABLE=API"

      - run:
          name: Push Image to Harbor
          command: |
            echo $HARBOR_PASSWORD | docker login ayazumman.xyz -u $HARBOR_USERNAME --password-stdin
            docker tag sad-final $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:$CIRCLE_SHA1

      - run:
          name: Install gcloud CLI
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            sudo apt-get update && sudo apt-get install google-cloud-cli

      - run:
          name: Authenticate gcloud CLI
          command: |
            echo "$GCLOUD_SERVICE_KEY" > /tmp/key.json
            gcloud auth activate-service-account --key-file=/tmp/key.json
            gcloud config set project $GOOGLE_PROJECT_ID

      - run:
          name: Deploy Docker Container to GCE Instance
          command: |
            gcloud compute ssh $GCE_INSTANCE_NAME --quiet --zone=$GCE_ZONE --command "
            echo $HARBOR_PASSWORD | docker login ayazumman.xyz -u $HARBOR_USERNAME --password-stdin &&
            docker pull $IMAGE_NAME:$CIRCLE_SHA1 &&
            docker stop sad-final || true &&
            docker rm sad-final || true &&
            docker run -d -p 443:443 -e ASPNETCORE_URLS='https://*:443' -e ConnectionStrings__DefaultConnection='$ConnectionStrings__DefaultConnection' -e JwtSettings__SecretKey='$JwtSettings__SecretKey' -e Google__ClientId='$Google__ClientId' -e Google__ClientSecret='$Google__ClientSecret' -e EmailSettings__UserName='sendinblue.brevo@gmail.com' -e EmailSettings__Password='$EmailSettings__Password' -e EmailSettings__From='sendinblue.brevo@gmail.com' -e EmailSettings__Port='465' -e EmailSettings__Provider='smtp-relay.brevo.com' -v /etc/letsencrypt/live/sad.ayazumman.xyz:/etc/ssl/certs:ro --name sad-final $IMAGE_NAME:$CIRCLE_SHA1 &&
            docker ps &&
            docker ps -a 
            "

workflows:
  build-and-push:
    jobs:
      - build
