version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: cimg/base:stable
    resource_class: medium

jobs:
  build:
    executor: dotnet-executor
    environment:
      IMAGE_NAME: ayazumman.xyz/circleci/sad-final
    steps:
      - checkout

      - run:
          name: Install .NET SDK
          command: |
            curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel LTS
            echo 'export PATH=$PATH:/home/circleci/.dotnet' >> $BASH_ENV

      - run:
          name: Restore and Build
          command: |
            source $BASH_ENV
            dotnet restore
            dotnet build

      - run:
          name: Run Tests
          command: dotnet test

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Image with Buildpacks
          command: |
            curl -sSL https://github.com/buildpacks/pack/releases/download/v0.35.1/pack-v0.35.1-linux.tgz | tar xz
            sudo mv pack /usr/local/bin/pack
            pack build sad-final --path ./API --builder gcr.io/buildpacks/builder:google-22

      - run:
          name: Push Image to Harbor
          command: |
            echo $HARBOR_PASSWORD | docker login -u $HARBOR_USERNAME --password-stdin
            docker tag sad-final $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:$CIRCLE_SHA1

workflows:
  build-and-push:
    jobs:
      - build
